"""debit table

Revision ID: 37f7582327fe
Revises: 63634acbf78c
Create Date: 2021-03-21 14:19:02.481280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f7582327fe'
down_revision = '63634acbf78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit', sa.Column('label', sa.String(), nullable=True))
    op.create_index(op.f('ix_debit_label'), 'debit', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debit_label'), table_name='debit')
    op.drop_column('debit', 'label')
    # ### end Alembic commands ###
