"""debits table

Revision ID: 63634acbf78c
Revises: 
Create Date: 2021-03-14 16:01:18.145628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63634acbf78c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_amount'), 'debit', ['amount'], unique=False)
    op.create_index(op.f('ix_debit_date'), 'debit', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debit_date'), table_name='debit')
    op.drop_index(op.f('ix_debit_amount'), table_name='debit')
    op.drop_table('debit')
    # ### end Alembic commands ###
